# Generated by Django 3.2.20 on 2023-09-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
