# Generated by Django 3.2.20 on 2023-09-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landrecords', '0002_logindata_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logindata',
            old_name='name',
            new_name='username',
        ),
    ]
