# Generated by Django 3.2.20 on 2023-09-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landrecords', '0004_newentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='newentry',
            name='code',
            field=models.ImageField(blank=True, upload_to='code'),
        ),
    ]
