# Generated by Django 3.2.22 on 2023-10-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landrecords', '0005_newentry_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newentry',
            name='code',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='district',
        ),
        migrations.RemoveField(
            model_name='newentry',
            name='fname',
        ),
    ]

