# Generated by Django 3.2.22 on 2023-10-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landrecords', '0006_auto_20231015_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='newentry',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
